DATA:
  BATCH_SIZE: 8
  FRAME_STRIDE: 4
  HEIGHT: 224
  NUM_FRAMES: 16
  NUM_WORKERS: 1
  ROOT: /fs/scratch/PAS3184/v3
  SHOT_TYPE: freethrow
  TRAIN_RATIO: 0.7
  VIDEO_TYPE: appearance
  WIDTH: 224
  USE_SAMPLER: true
  NUM_INSTANCES: 4
  SAMPLE_START: middle
  SPLIT_SAMPLING: false
  USE_PRESPLIT: false
GPU_IDS:
- 0
LOSS:
  ID_WEIGHT: 1.0
  LABEL_SMOOTH_EPSILON: 0.1
  TRIPLET_DISTANCE: euclidean
  TRIPLET_MARGIN: 0.3
  TRIPLET_WEIGHT: 1.0
  USE_LABEL_SMOOTH: true
  USE_TRIPLET: true
MODEL:
  ARCH: ''
  CHECKPOINT_NUM:
  - 0
  MODEL_NAME: VideoMAEv2ReID
  NAME: VideoMAEv2ReID
  NUM_CLASSES: 0
  USE_CHECKPOINT: true
NUM_GPUS: 1
OUTPUT_DIR: ./outputs/VideoMAEv2_v3_appearance_middle_nosplitsampling
REID:
  EMBED_DIM: 512
  NECK_FEAT: after
SEED: 42
SOLVER:
  BASE_LR: 1e-4
  CHECKPOINT_PERIOD: 10
  CLIP_GRADIENTS:
    CLIP_VALUE: 1.0
    ENABLED: true
  COSINE_AFTER_WARMUP: true
  COSINE_END_LR: 1.0e-07
  EVAL_PERIOD: 1
  GAMMA: 0.1
  LOG_PERIOD: 1
  MAX_EPOCHS: 100
  MOMENTUM: 0.9
  OPTIMIZER: AdamW
  STEPS:
  - 40
  - 70
  WARMUP_EPOCHS: 0
  WEIGHT_DECAY: 0.05
TEST:
  BATCH_SIZE: 16
  WEIGHT: ''
VIDEOMAEV2:
  MODEL: vit_base_patch16_224
  PRETRAIN: /users/PAS2985/cz2128/ReID/VideoMAEv2/model_zoo/vit_b_k710_dl_from_giant.pth
  MODEL_KEY: model|module|state_dict
  TUBELET_SIZE: 2
  DROP_RATE: 0.2
  ATTN_DROP_RATE: 0.0
  DROP_PATH_RATE: 0.0
  HEAD_DROP_RATE: 0.0
  USE_MEAN_POOLING: true
  INIT_SCALE: 0.0
  WITH_CHECKPOINT: false
  COS_ATTENTION: false
  FROZEN: false