MODEL:
  ARCH: "mvit"
  MODEL_NAME: "MViT"
  NUM_CLASSES: 99

DATA:
  NUM_FRAMES: 16
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]

MVIT:
  MODE: "conv"
  CLS_EMBED_ON: True
  PATCH_KERNEL: [3, 7, 7]
  PATCH_STRIDE: [2, 4, 4]
  PATCH_PADDING: [1, 3, 3]
  EMBED_DIM: 96
  NUM_HEADS: 1
  MLP_RATIO: 4.0
  QKV_BIAS: True
  DROPPATH_RATE: 0.2
  DEPTH: 16
  NORM: "layernorm"
  USE_ABS_POS: False
  REL_POS_SPATIAL: True
  REL_POS_TEMPORAL: True
  SEP_POS_EMBED: False
  USE_FIXED_SINCOS_POS: False
  DIM_MUL_IN_ATT: True
  RESIDUAL_POOLING: True
  USE_MEAN_POOLING: False
  DIM_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  POOL_KVQ_KERNEL: [3, 3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  POOL_Q_STRIDE: [
    [0, 1, 1, 1], [1, 1, 2, 2], [2, 1, 1, 1], [3, 1, 2, 2],
    [4, 1, 1, 1], [5, 1, 1, 1], [6, 1, 1, 1], [7, 1, 1, 1],
    [8, 1, 1, 1], [9, 1, 1, 1], [10, 1, 1, 1], [11, 1, 1, 1],
    [12, 1, 1, 1], [13, 1, 1, 1], [14, 1, 2, 2], [15, 1, 1, 1]
  ]
  PRETRAIN: ""
  FROZEN: False

REID:
  EMBED_DIM: 512
  NECK_FEAT: "after"
