DATA:
  BATCH_SIZE: 16
  FRAME_STRIDE: 4
  HEIGHT: 224
  NUM_FRAMES: 16
  NUM_INSTANCES: 4
  NUM_WORKERS: 4
  ROOT: /fs/scratch/PAS3184/v2
  SHOT_TYPE: freethrow
  TRAIN_RATIO: 0.7
  USE_SAMPLER: true
  VIDEO_TYPE: mask
  WIDTH: 224
GPU_IDS:
- 0
LOSS:
  ID_WEIGHT: 1.0
  LABEL_SMOOTH_EPSILON: 0.1
  TRIPLET_DISTANCE: euclidean
  TRIPLET_MARGIN: 0.3
  TRIPLET_WEIGHT: 1.0
  USE_LABEL_SMOOTH: true
  USE_TRIPLET: true
MODEL:
  ARCH: uniformerv2
  CHECKPOINT_NUM:
  - 0
  MODEL_NAME: Uniformerv2ReID
  NAME: Uniformerv2ReID
  NUM_CLASSES: 99
  USE_CHECKPOINT: true
NUM_GPUS: 1
OUTPUT_DIR: ./outputs/uniformerv2_freethrow_mask_k400_16frames_1e-4
REID:
  EMBED_DIM: 768
  NECK_FEAT: after
SEED: 42
SOLVER:
  BASE_LR: 0.0001
  CHECKPOINT_PERIOD: 10
  CLIP_GRADIENTS:
    CLIP_VALUE: 1.0
    ENABLED: true
  COSINE_AFTER_WARMUP: true
  COSINE_END_LR: 1.0e-06
  EVAL_PERIOD: 1
  GAMMA: 0.1
  LOG_PERIOD: 1
  MAX_EPOCHS: 100
  MOMENTUM: 0.9
  OPTIMIZER: AdamW
  STEPS:
  - 40
  - 70
  WARMUP_EPOCHS: 50
  WEIGHT_DECAY: 0.05
TEST:
  BATCH_SIZE: 16
  WEIGHT: ''
UNIFORMERV2:
  BACKBONE: uniformerv2_b16
  BACKBONE_DROP_PATH_RATE: 0.0
  CLS_DROPOUT: 0.5
  DOUBLE_LMHRA: true
  DROP_PATH_RATE: 0.0
  DW_REDUCTION: 1.5
  FROZEN: false
  MLP_DROPOUT:
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  MLP_FACTOR: 4.0
  NO_LMHRA: false
  N_DIM: 768
  N_HEAD: 12
  N_LAYERS: 4
  PRETRAIN: ''
  RETURN_LIST:
  - 8
  - 9
  - 10
  - 11
  TEMPORAL_DOWNSAMPLE: false
