DATA:
  BATCH_SIZE: 16
  FRAME_STRIDE: 4
  HEIGHT: 224
  NUM_FRAMES: 16
  NUM_WORKERS: 8
  ROOT: /fs/scratch/PAS3184/v3
  SHOT_TYPE: freethrow
  TRAIN_RATIO: 0.7
  VIDEO_TYPE: mask
  WIDTH: 224
  USE_SAMPLER: True
  SAMPLE_START: beginning
  SPLIT_SAMPLING: False
  NUM_INSTANCES: 4
  NUM_SPLIT: 120
GPU_IDS:
- 0
LOSS:
  ID_WEIGHT: 1.0
  LABEL_SMOOTH_EPSILON: 0.1
  TRIPLET_DISTANCE: euclidean
  TRIPLET_MARGIN: 0.3
  TRIPLET_WEIGHT: 1.0
  USE_LABEL_SMOOTH: true
  USE_TRIPLET: true
MODEL:
  ARCH: mvit
  MODEL_NAME: MViTReID
  NAME: MViTReID
  NUM_CLASSES: 0
  USE_CHECKPOINT: true
NUM_GPUS: 1
OUTPUT_DIR: ./outputs/rebuttal/mask_120split
REID:
  EMBED_DIM: 512
  NECK_FEAT: after
SEED: 42
SOLVER:
  BASE_LR: 0.0001
  CHECKPOINT_PERIOD: 10
  CLIP_GRADIENTS:
    CLIP_VALUE: 1.0
    ENABLED: true
  COSINE_AFTER_WARMUP: true
  COSINE_END_LR: 1.0e-06
  EVAL_PERIOD: 5
  GAMMA: 0.1
  LOG_PERIOD: 1
  MAX_EPOCHS: 100
  MOMENTUM: 0.9
  OPTIMIZER: AdamW
  STEPS:
  - 30
  - 40
  WARMUP_EPOCHS: 0
  WEIGHT_DECAY: 0.05
TEST:
  BATCH_SIZE: 16
  WEIGHT: ''
MVIT:
  PRETRAIN: /users/PAS2099/clydewu117/nba_reid/checkpoints/mvitv2/MViTv2_S_16x4_k400_f302660347.pyth
  FROZEN: false
  USE_MEAN_POOLING: false
  CLS_EMBED_ON: true
  EMBED_DIM: 96
  NUM_HEADS: 1
  MLP_RATIO: 4.0
  DROPPATH_RATE: 0.3
  DEPTH: 16
  PATCH_KERNEL: [3, 7, 7]
  PATCH_STRIDE: [2, 4, 4]
  PATCH_PADDING: [1, 3, 3]
  DIM_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  POOL_Q_STRIDE: [[0, 1, 1, 1], [1, 1, 2, 2], [2, 1, 1, 1], [3, 1, 2, 2], [4, 1, 1, 1], [5, 1, 1, 1], [6, 1, 1, 1], [7, 1, 1, 1], [8, 1, 1, 1], [9, 1, 1, 1], [10, 1, 1, 1], [11, 1, 1, 1], [12, 1, 1, 1], [13, 1, 1, 1], [14, 1, 2, 2], [15, 1, 1, 1]]
  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  POOL_KVQ_KERNEL: [3, 3, 3]
